(function() {var implementors = {};
implementors["rusoto_core"] = ["impl&lt;T, E&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/struct.RusotoFuture.html\" title=\"struct rusoto_core::RusotoFuture\">RusotoFuture</a>&lt;T, E&gt;","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/request/struct.BufferedHttpResponseFuture.html\" title=\"struct rusoto_core::request::BufferedHttpResponseFuture\">BufferedHttpResponseFuture</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/request/struct.HttpClientFuture.html\" title=\"struct rusoto_core::request::HttpClientFuture\">HttpClientFuture</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/reactor/struct.RequestDispatcherFuture.html\" title=\"struct rusoto_core::reactor::RequestDispatcherFuture\">RequestDispatcherFuture</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/reactor/struct.CredentialsProviderFuture.html\" title=\"struct rusoto_core::reactor::CredentialsProviderFuture\">CredentialsProviderFuture</a>",];
implementors["rusoto_credential"] = ["impl&lt;P:&nbsp;<a class=\"trait\" href=\"rusoto_credential/trait.ProvideAwsCredentials.html\" title=\"trait rusoto_credential::ProvideAwsCredentials\">ProvideAwsCredentials</a> + 'static&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.AutoRefreshingProviderFuture.html\" title=\"struct rusoto_credential::AutoRefreshingProviderFuture\">AutoRefreshingProviderFuture</a>&lt;P&gt;","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.ChainProviderFuture.html\" title=\"struct rusoto_credential::ChainProviderFuture\">ChainProviderFuture</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
